insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-2', '第二章：地理空间数学基础', '地球参考、投影、尺度与格网', 2, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-2';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 0, '地理空间的数学基础主要包括哪三个方面？', '地球空间参考、空间数据投影及坐标转换、空间尺度及地理格网。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 1, '地球表面的几何模型通常分为哪四类？', '地球自然表面、大地水准面、地球椭球面、数学模型。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 2, '什么是“大地水准面”？', '假设海水处于静止平衡状态并延伸到大陆下部，与重力方向处处正交的连续闭合水准面。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 3, '在大地测量和 GIS 应用中，通常选择什么作为地球的理想模型？', '旋转椭球（地球椭球）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 4, '地球椭球的数学表达式中，参数 $a$ 和 $b$ 分别代表什么？', '$a$ 为长半径（近似赤道半径），$b$ 为极轴半径。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 5, '中国 1980 西安坐标系所采用的参考椭球是什么？', '1975 年国际椭球。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 6, '什么是“椭球定位”？', '依据一定条件，将具有给定参数的椭球与大地体的相关位置确定下来。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 7, '参考定位与绝对定位的主要区别是什么？', '参考定位强调局部符合（如西安 80），绝对定位强调全球符合（如 WGS 84）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 8, '球面坐标系统主要由哪两个基本参数组成？', '一个地球椭球和一个大地基准面。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 9, '平面坐标系统在包含球面坐标系统参数的基础上，还必须指定什么？', '投影规则（映射关系）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 10, '天文地理坐标系是以什么为依据建立的？', '大地体（垂线方向）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 11, '参心空间直角坐标系的原点位于何处？', '参考椭球的中心。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 12, '地心空间直角坐标系的原点位于何处？', '地球质心。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 13, '中国从 2008 年起启用的地心坐标系统简称为什么？', 'CGCS2000（2000 国家大地坐标系）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 14, '在高斯平面直角坐标系中，规定以什么为 $X$ 轴？', '中央经线。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 15, '在高斯平面直角坐标系中，规定以什么为 $Y$ 轴？', '赤道。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 16, '为了避免 $y$ 值出现负值，高斯坐标系规定各投影带的坐标纵轴向西移动多少距离？', '$500\text{ km}$。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 17, '高斯通用坐标（如 $19\ 738765.2\text{ m}$）前两位数字表示什么？', '投影带的编号。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 18, '建立“地方独立平面直角坐标系”的主要目的是什么？', '减小高斯投影产生的长度变形。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 19, '什么是“高程系统”？', '相对于不同性质的参考面（如大地水准面、地球椭球面）所定义的高程体系。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 20, '以地球椭球面为参考面的高程称为什么？', '大地高。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 21, '什么是“深度基准”？', '海图图载水深及其相关要素的起算面。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 22, '深度基准面的选择必须遵循哪两个原则？', '保证航行安全和充分利用航道。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 23, '地图投影的实质是什么？', '建立地面地理坐标 $(B, L)$ 与地图平面坐标 $(X, Y)$ 之间一一对应的函数关系。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 24, '地图投影的变形通常分为哪三种？', '长度变形、面积变形、角度变形。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 25, '长度比 $\mu$ 的定义是什么？', '投影后的微分线段长度 $ds''$ 与实地长度 $ds$ 之比（$\mu = \frac{ds''}{ds}$）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 26, '若面积比 $P=1$，则该投影属于什么性质的投影？', '等面积投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 27, '等角投影又常被称为什么投影？', '正形投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 28, '几何投影按辅助投影面的类型可分为哪三类？', '方位投影、圆柱投影、圆锥投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 29, '什么是“正轴投影”？', '投影面的中心轴与地轴重合。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 30, '伪圆柱投影的纬线和经线形状有何特征？', '纬线为平行直线，中央经线为直线，其余经线为对称曲线。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 31, '高斯-克吕格投影在投影分类上属于哪种类型？', '横轴等角切圆柱投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 32, '高斯投影中，长度变形在何处达到最大？', '边缘处（赤道与带边缘交点）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 33, '高斯投影 $6^{\circ}$ 带第 1 带的中央经线是多少度？', '$3^{\circ}\text{ E}$。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 34, '中国 $1:1$ 万比例尺地形图采用几度分带？', '$3^{\circ}$ 分带。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 35, 'UTM 投影与高斯投影的主要区别之一是中央经线的长度比，UTM 规定为多少？', '$0.9996$。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 36, '兰勃特等角投影（Lambert）通常属于哪种几何投影？', '正轴等角割圆锥投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 37, '中国全图（含南海诸岛插图）常用的投影是什么？', '正轴等面积割圆锥投影（Lambert 投影）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 38, '在东西延伸的中纬度地区（如中国），一般多采用哪种投影？', '正轴圆锥投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 39, '在南北方向延伸的地区（如智利），一般采用什么投影？', '横轴圆柱投影或多圆锥投影。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 40, '同一地理坐标基准下的坐标变换，若无直接解析式，通常采用什么方法？', '间接变换（反算回球面坐标再正算到新投影）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 41, '多项式拟合变换主要应用于什么情况？', '无法获取参与转换的空间参考投影信息时。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 42, '地图比例尺的数字式表示法举例。', '$1:100000$ 或 $1:10$ 万。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 43, '什么是数字地图中的“无级比例尺”概念？', '数据存储在计算机中，可以根据需要按比例任意缩小或放大，不固定在单一比例尺。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 44, '空间分辨率的定义是什么？', '图像中目标空间细节可分辨的最小尺寸。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 45, '什么是“操作尺度”？', '对空间实体、现象数据进行处理操作时应采用的最佳尺度。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 46, '地理坐标格网（经纬度坐标）的主要缺点是什么？', '实地大小不均匀（高纬度小，低纬度大）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-2', 47, '直角坐标格网的主要优点是什么？', '实地格网大小均匀。', datetime('now'));
