insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-1', '第一章：概论', 'GIS 基础概念与发展', 1, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-1';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 0, '数据（Data）在认识世界过程中被定义为何种形式的记录？', '是对事物和环境描述的直接或间接原始记录，是未经加工的原始资料。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 1, '信息（Information）区别于数据的本质特征是什么？', '信息是数据内涵的意义，是提供关于现实世界新的事实和知识的依据。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 2, '在地理信息系统中，“信息是数据的表达，数据是信息的_____”。', '载体', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 3, '信息具有的四个基本特征包括客观性、适用性、可传输性和_____。', '共享性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 4, '地理数据（Geographical Data）的五个核心特征是什么？', '空间上的分布性、时间上的序列性、数量上的海量性、载体的多样性、位置与属性的对应性。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 5, '地理数据特征中的“空间上的分布性”遵循什么逻辑顺序？', '先定位，后定性。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 6, '地理对象或现象的数据描述由哪三部分组成？', '空间位置、属性数据（非空间数据）、时域数据。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 7, '空间位置数据除了可以根据大地参照系定义坐标，还可以定义为地物间的什么关系？', '相对位置关系（如空间上的相邻、包含等）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 8, '属性数据（Attribute Data）主要解决的是地理环境研究中的什么问题？', '按照专题来表达多维和多层次的非空间属性信息。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 9, '时域数据（Temporal Data）在地理信息系统中的主要作用是什么？', '记录数据采集或现象发生的时刻/时段，对环境模拟分析至关重要。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 10, '地理信息独特的“空间相关性”特征遵循什么规律？', '地理事物在空间上相距越近相关性越大，反之越小，且具有区域性特点。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 11, '地理信息“空间多样性”对分析结果的解释提出了什么要求？', '分析结果必须依赖于其位置，才能得出合乎逻辑的解释。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 12, '地理信息“空间层次性”在尺度上如何体现？', '不同空间尺度的数据具有不同的空间信息特征。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 13, '按处理对象分类，信息系统可分为空间信息系统和_____。', '非空间信息系统', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 14, '在应用层次上，地理信息系统（GIS）属于哪一类系统？', '决策支持系统', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 15, 'GIS 与其他信息系统在操作对象上的根本区别是什么？', 'GIS 的对象是按统一地理坐标编码的空间数据（点、线、面、体）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 16, 'GIS 被誉为地学的第几代语言？', '第三代语言（用数字形式描述空间实体）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 17, '为什么说 GIS 中的属性信息处理相当于普通的事务性信息处理系统？', '因为属性数据描述的是除空间位置及关系外的定性或定量信息。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 18, 'GIS 空间数据管理中，相对于事务性数据，其最显著的物理特征是什么？', '不定长性（如多边形顶点数量不一）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 19, '地理信息系统海量数据的来源主要包括地理数据本身和_____。', '空间分析过程中不断产生的新空间数据。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 20, 'GIS 运行环境的五大部分组成是什么？', '硬件系统、软件系统、空间数据、地学模型、管理与应用人员。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 21, 'GIS 软件系统架构从底层到顶层依次是什么？', 'GIS 支撑软件、GIS 平台软件、GIS 应用软件。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 22, '操作系统（如 Windows, Linux）和数据库管理系统（如 Oracle）属于 GIS 软件的哪一类？', 'GIS 支撑软件', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 23, 'GIS 平台软件的主要表现形式包括基础应用程序和_____。', '软件开发包（SDK）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 24, 'GIS 应用软件与平台软件的关系是什么？', '应用软件是基于平台软件提供的功能和接口，针对行业具体业务需求二次开发而成的。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 25, '在 GIS 数据中，用于表示点、线、面实体之间联系的关系称为什么？', '拓扑关系（Topology）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 26, '定性属性数据包括名称、类型、特性等，定量属性数据则包括_____。', '数量和等级', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 27, '地学模型（Geoscientific Model）在 GIS 中的作用是什么？', '构建能表达或模拟特定现象的计算机模型，为复杂应用提供解决方案。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 28, 'GIS 解决的 5 个基本地理问题是什么？', '位置（Location）、条件（Condition）、趋势（Trend）、模式（Pattern）、模拟（Simulation）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 29, 'GIS 的“位置”问题主要通过哪种技术实现？', '空间查询技术', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 30, '“符合某些条件的地理对象在哪里”属于 GIS 解决的哪类基本问题？', '条件问题', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 31, '“趋势”问题要求 GIS 具备根据历史数据进行哪种分析的能力？', '预测未来和回溯过去。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 32, 'GIS 的“模式”问题主要探讨地理实体分布之间的什么？', '空间关系', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 33, 'GIS 的 6 个基本功能模块包括数据采集、编辑处理、存储管理、分析查询、应用开发和_____。', '数据输出与可视化表达', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 34, '目前常用的 GIS 空间数据结构主要有矢量数据结构和_____。', '栅格数据结构', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 35, '数据可视化表达中，传递空间信息最有效的工具是什么？', '图形（地图）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 36, 'GIS 功能中的“二次开发”通常提供什么支持？', '完整的 API（应用程序接口）和开发环境。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 37, '测量学和遥感技术在 GIS 中扮演的主要角色是什么？', '提供快速、可靠、多时相和廉价的多种信息源。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 38, 'GIS 空间分析的理论基础主要由哪门学科提供？', '地理学', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 39, 'GIS 最初是从哪种技术起步的？', '机助制图（Computer-Aided Cartography）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 40, 'GIS 与数字制图系统的主要区别在于什么？', '深层次的空间分析功能（如缓冲区分析、叠置分析等）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 41, '相对于 CAD，GIS 在数据处理上的强项是什么？', '属性功能强，能够处理复杂的地理空间自然目标，且具有强大的海量数据图库管理能力。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 42, '遥感图像处理系统强调对栅格数据的几何和灰度处理，而 GIS 更侧重于实体的什么描述？', '空间关系描述及属性查询。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 43, '1998 年由美国副总统戈尔提出的概念是_____。', '数字地球（Digital Earth）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 44, '被称为第三代互联网应用，旨在实现资源全面共享的 GIS 模式是_____。', '网格 GIS（GRID GIS）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 45, 'VR GIS 采用哪种主要语言将数据转换到虚拟环境中？', 'VRML（虚拟现实建模语言）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 46, '移动 GIS 实现“4A 服务”指哪四个方面？', '任何地方、任何时间、任何人、任何事 (Anywhere, Anytime, Anyone, Anything)。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 47, '智慧城市建设中，动态获取城市空间物联信息的基础基建是什么？', '物联网（IoT）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 48, '云计算数据中心为 GIS 用户提供的核心价值不再是硬件设备，而是_____。', '计算能力和可用性的各项功能。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 49, '时空大数据相比传统数据，在特征上表现出更强的动态性和_____。', '流动性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 50, '在大数据 GIS 中，哪种计算技术在数据处理和分析环节发挥重要作用？', '并行计算（如 Hadoop, Spark）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 51, '机器学习相比传统数据挖掘在 GIS 分析中的优势是什么？', '算法带有自调试参数，能通过学习自我完善，提高挖掘和预测的准确性。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 52, '1:5 万与 1:1 万坡度分级数据的差异，体现了地理信息的哪种特性？', '空间尺度上的层次性。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 53, 'GIS 的物理外壳是_____。', '计算机化的技术系统', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-1', 54, '为什么地理数据库的更新应当是分布式的？', '因为地理信息在区域上表现出分布式特点，且属性表现为多层次。', datetime('now'));
