insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-3', '第三章：空间数据模型', '空间实体、关系、场与数据模型', 3, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-3';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 0, '地理学中，地理空间（geographic space）通常指什么范围？', '地球表面及近地表空间。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 1, '空间实体具有哪四个基本特征？', '空间位置特征、属性特征、时间特征和空间关系特征。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 2, '空间实体的_____也称为几何特征，包括其位置、大小、形状和分布状况。', '空间位置特征', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 3, '空间实体的_____特征也称为非空间特征或专题特征。', '属性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 4, '空间实体的属性通常分为定性属性（如名称）和_____属性（如数量、等级）。', '定量', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 5, '地理空间中实体之间密切联系的特性称为什么？', '空间关系', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 6, '空间关系主要包括拓扑关系、度量关系和_____关系。', '顺序', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 7, '在GIS抽象过程中，哪一个层次是系统抽象的最高层？', '概念模型（Conceptual Model）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 8, '哪种数据模型是概念模型向物理模型转换的桥梁，通常指空间数据的逻辑结构？', '逻辑数据模型', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 9, '_____模型是概念模型在计算机内部具体的存储形式和操作机制，涉及磁盘存放。', '物理数据模型', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 10, '将整个地理空间看作空域，其中的地理现象作为独立对象分布，这种模型称为_____模型。', '对象（要素）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 11, '对象模型通常将空间特征划分为哪四种基本形式？', '点、线、面、体。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 12, '哪种概念模型适合描述大气污染、地表温度、地形高度等连续变化的现象？', '场模型（Field Model）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 13, '二维场模型在数学上通常表示为函数 $A = f(x, y)$，其中 $x, y$ 代表什么？', '空间位置坐标', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 14, '在场数据模型中，不规则三角形区（TIN）任意位置的属性值通常通过什么方法得到？', '线性内插', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 15, '场数据模型中，将平面划分为间距相等的矩形单元进行属性记录的方式称为_____。', '规则格网（Grid）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 16, '网络模型与对象模型的主要区别在于它强调地理对象之间的_____。', '交互作用（或连通情况）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 17, '时空数据模型主要用于表达地理现象随时间变化的动态过程，其三个基本要素是_____。', '空间、时间和属性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 18, '时间地理学中，用于定量表达活动个体行为轨迹的模型是_____。', '时空棱柱（Space-time prism）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 19, '时空立方体（Space-time cube）模型属于_____型时空数据模型。', '连续', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 20, '在GIS中，如果地理现象随坐标 $x, y, h$（高程）和 $t$（时间）四个变量变化，需构建_____模型。', '四维数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 21, '对于现状不定的现象（如火灾、洪水扩散），通常首选哪种概念模型进行建模？', '场模型', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 22, '在面向对象模型中，将具有相同属性和方法的实体归类抽象的过程称为_____。', '分类（Classification）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 23, '“概括”（Generalization）是将多个类进一步抽象为_____的过程。', '超类（Super-class）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 24, '面向对象技术中，强制性地将子对象的属性信息传递给复杂对象的工具称为_____。', '传播（Propagation）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 25, '几何图形数据中，连接两个结点的线段通常称为_____或链（link）。', '弧段（arc）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 26, '在二维平面上，点 $P$ 存储为 $(x, y)$；若含有高程信息则存储为 $(x, y, z)$，后者称为_____要素。', '三维点', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 27, '矢量数据的基本结构类型中，面（Area）属于几维数据？', '二维数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 28, '像素数据的最小分割单元通常称为什么？', '像元（Pixel）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 29, '影像数据的空间分辨率是指像元大小所对应的_____。', '地面覆盖面积尺寸', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 30, '对于影像数据，分辨率越高（像元越小），显示的细节越_____。', '多（或详细）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 31, '为什么地图比例尺变大不代表分辨率提高？', '因为实际像元代表的地面覆盖面积（像元大小）并未改变。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 32, '在确定栅格单元值时，取像元几何中心点的值作为该单元属性的方法称为_____。', '中心点取值法', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 33, '拓扑关系中的“邻接关系”是指哪类元素之间的关系？', '同类元素（如多边形与多边形）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 34, '拓扑关系中的“关联关系”是指哪类元素之间的关系？', '不同类元素（如结点与弧段）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 35, '拓扑空间关系中，描述一个实体完全处于另一个实体内部的关系是_____。', '包含（或包含于/覆盖）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 36, '在空间数据拓扑关系表中，弧段的“左邻面”和“右邻面”是如何确定的？', '沿弧段前进方向确定', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 37, '点实体与面实体之间可能存在哪三种拓扑关系？', '相邻、相离、包含。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 38, '描述实体间东南西北方位关系的空间关系属于_____空间关系。', '顺序', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 39, '描述空间实体之间距离远近的关系属于_____空间关系。', '度量', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 40, '哪种对象抽象技术将属于同一类的若干对象组合成新的集合，表现为“is member of”关系？', '联合（Association）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 41, '在GIS中，通常使用哪种图形建模语言来表达数据逻辑模型？', 'UML（统一建模语言）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 42, '封闭的多面体（Multipatch）主要用于表示哪种地理对象？', '三维地理对象（如建筑物、道路体）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 43, '空间数据类型中，关于数据的数据（如来源、精度、比例尺等）称为什么？', '元数据（Metadata）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 44, '在场模型表示方法中，等值线中间区域的属性值是如何确定的？', '通过两条等值线的连续插值。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 45, '矢量数据的构建基础是什么？', '点的位置及其序列关系。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-3', 46, '在城市地籍管理中，将宗地边界与内部建筑物聚集为“宗地”类，这体现了哪种建模思想？', '面向对象建模（或聚集技术）', datetime('now'));
