insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-5', '第五章：空间数据组织与管理', '空间数据库、组织方式与空间索引', 5, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-5';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 0, '空间信息技术由空间数据获取、空间数据处理以及_____三个部分组成。', '空间数据应用技术', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 1, '在空间信息技术的三大组成部分中，哪项技术被视为基础和核心？', '空间数据管理', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 2, '通用数据库是建立在_____数据基础上的，它是文件管理的高级阶段。', '结构化', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 3, '数据库是长期储存在计算机内的、有组织的、可_____的数据集合。', '共享', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 4, '在数据库发展的早期，层次模型和_____模型统称为非关系模型。', '网状', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 5, '20 世纪 80 年代以来，哪种模型因其能够描述复杂对象而促进了数据库研究的发展？', '面向对象模型 (Object Oriented Model)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 6, '空间数据库是某一区域内关于一定_____特征的数据集合。', '地理要素', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 7, '空间数据库与一般数据库相比，其数据量具有什么显著特征？', '数据量特别大（海量数据特征）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 8, '空间数据的“多尺度与多态性”特征是指什么？', '不同比例尺具有不同精度，且同一地物在不同情况下形态存在差异。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 9, '在空间数据库中，栅格数据库通常包括遥感影像数据和 _____ 数据。', 'DEM (数字高程模型)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 10, '矢量数据库主要由图形数据和_____数据组成。', '属性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 11, '在空间数据库设计阶段，将河流建模为线要素还是面要素，属于哪一方面的内容？', '选择数据模型与划分地理实体', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 12, '地理实体的“行为”通常是通过定义要素之间的_____关系和拓扑关系实现的。', '一般空间', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 13, 'GIS 数据库设计的第一步通常是确定_____与目标信息产品。', '业务需求', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 14, '在设计中，使用_____（如拓扑、网络）来建模图层中及数据集间各元素的关系。', '高级数据类型', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 15, '在数据库设计记录中，虽然常用，但无法表示所有地理属性和 GIS 设计理念的工具是 _____。', 'UML (统一建模语言)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 16, '空间数据由于每条记录长度不一（如弧段坐标对数量不同），表现出明显的_____特征。', '非结构化', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 17, '除了坐标隐含的分布关系外，空间数据还通过_____数据结构表达复杂的空间关系。', '拓扑', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 18, '空间数据的分层组织是按照地理事物的分类、专题内容或_____类别来设定图层的。', '要素几何', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 19, '空间数据分块组织的优点是可以提高数据_____的效率。', '存取 (存储与管理)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 20, '哪种无缝组织形式仅在视觉上连续，但物理上仍然采用图幅或分块存储？', '几何无缝', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 21, '逻辑无缝组织在分幅边界处对要素进行逻辑接边，并建立跨图幅的_____。', '唯一标识 (或链接关系/索引结构)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 22, '为了在大范围区域提供不同细节层次的刻画，需要建立_____空间数据库。', '多尺度 (或多比例尺)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 23, '多尺度空间数据库构建中，由一个大比例尺库动态生成其他比例尺数据的方式称为_____方式。', '动态', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 24, '在属性数据组织中，通常将各类属性按_____表进行数据组织，以便利用商业 DBMS。', '二维', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 25, 'ArcGIS 采用的属性组织方式中，每个地物类通过_____与 AAT 或 PAT 表相连。', '地物编码和内部连接码', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 26, '矢量数据的管理方式主要包括文件/关系数据库混合管理、全关系管理和_____管理。', '对象关系数据库', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 27, '文件-关系数据库混合管理模式中，通常用_____管理几何图形数据。', '文件系统', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 28, '全关系数据库管理方式中，通常将变长的几何数据处理成_____字段进行存储。', 'Binary 二进制 Block (或 BLOB)', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 29, '在栅格数据管理中，如果不放入数据库，仅在数据库中存储文件路径和标识号，这种方式称为_____方式。', '文件-数据库管理', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 30, 'SQL 语言中，用于数据定义的动词包括 Create、Drop 和 _____。', 'Alter', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 31, 'SQL 语言中，用于数据查询的唯一动词是 _____。', 'Select', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 32, '通用横轴墨卡托投影的英文缩写是什么？', 'UTM', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-5', 33, '多比例尺空间数据库最主要的构建方式是_____构建方式。', '静态 (事先分别构建)', datetime('now'));
