insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-6', '第六章：空间数据的采集与处理', '数据源、数字化、编辑、变换与质量控制', 6, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-6';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 0, '地理信息系统（GIS）的核心环节包括数据的采集、处理、存储、_____和表现。', '分析', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 1, 'GIS 数据采集工作主要包括空间数据的采集和_____的采集。', '属性数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 2, 'GIS 数据源按获取方式可分为：地图数据、遥感影像数据、实测数据、_____和其它数据。', '共享数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 3, 'GIS 数据源按表现方式可分为：数字化数据、_____及文本资料数据。', '多媒体数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 4, '作为 GIS 最主要数据源之一，经过数字化处理的资料是_____。', '国家基本比例尺系列地形图', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 5, '遥感影像数据的主要优点包括现势性强、获取面积大以及_____。', '周期性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 6, '在应用地图数据时，必须注意纸质介质在不同存放条件下存在的_____。', '变形', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 7, '在使用不同投影的地图数据进行交流前，必须先进行_____的转换。', '地图投影', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 8, '许多部门和机构拥有的统计资料通常是 GIS _____的重要来源。', '属性数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 9, '互联网数据作为 GIS 大数据来源，其主要的获取方式是_____。', '网络爬虫', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 10, '空间数据采集与处理的基本流程包括：数据源选择、_____、编辑处理、质量评价和数据入库。', '采集方法确定', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 11, '在选择数据源时，如果两种源的精度差别不大，应优先采用_____。', '有使用经验的传统数据源', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 12, '地图数据的采集通常采用_____的方法。', '扫描矢量化', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 13, '图形拼接、拓扑生成和数据压缩属于数据采集流程中的_____环节。', '数据的编辑与处理', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 14, '数据质量的控制和评价是系统分析结果_____的前提条件之一。', '可靠性', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 15, '按照空间数据管理要求，将成果数据导入空间数据库的过程称为_____。', '数据入库', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 16, '野外数字测图模式中，利用简码或草图记录的是碎部点的_____信息。', '绘图', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 17, '“全站仪 + 便携机 + 测图软件”构成的野外作业方式被称为_____。', '电子平板测绘', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 18, '地图数字化流程：扫描 $\rightarrow$ _____ $\rightarrow$ 矢量化 $\rightarrow$ 矢量编辑 $\rightarrow$ 格式转换。', '栅格编辑', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 19, '扫描矢量化中，手动跟踪屏幕图像的方式称为_____矢量化。', '屏幕鼠标跟踪', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 20, '倾斜摄影测量相较于人工建模，其显著优势在于提高了_____。', '生产效率', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 21, '遥感成像的基本原理是传感器记录地表各类地物对_____的反射特性。', '太阳辐射', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 22, '遥感数据处理中，旨在消除辐射畸变的处理称为_____。', '辐射量校正', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 23, '遥感图像处理流程中，最终确定图像数据与类别对应关系的环节是_____。', '分类处理', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 24, '遥感影像分类处理的结果通常以_____的形式输出。', '专题图', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 25, '为了将模拟遥感影像输入处理系统，必须进行 _____ 变换。', 'A/D（模数）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 26, '在城市规划管理 GIS 中，起重要参考作用的数据源是_____。', '文本资料数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 27, '通过摄影测量技术可以从立体像对中获取_____数据。', '地形', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 28, '在数字化过程中，处理中间色调像元通常可以通过选择合适的_____来实现。', '阈值', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 29, '遥感数据处理内容中的“变换”旨在通过投影映射来_____图像信息。', '增强', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 30, '普通地图主要表达居民地、交通网、境界以及_____等自然和社会经济要素。', '地貌', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 31, '作为 GIS 数据源，专题地图着重反映地质、土壤、_____等特定专题要素。', '植被', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 32, '手机信令数据属于物联网数据中的_____部分。', '城市社会物联网大数据', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 33, '对于已有数据的采用，需格外关注数据精度和_____问题。', '可信度', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 34, '测量所得的碎部点三维坐标属于测绘成果中的_____数据。', '定位', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 35, '在数字化处理中，将栅格文件转换为矢量文件的过程称为_____。', '矢量化', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-6', 36, '倾斜摄影测量技术在欧美国家已广泛应用于国土安全、城市管理和_____等行业。', '房产税收', datetime('now'));
