insert into chapters (chapter_id, title, description, sort_order, updated_at) values ('chapter-4', '第四章：空间数据结构', '矢量结构、栅格结构与拓扑编码', 4, datetime('now')) on conflict(chapter_id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order, updated_at = excluded.updated_at;
delete from cards where chapter_id = 'chapter-4';
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 0, '什么是空间数据结构？', '对空间数据逻辑模型描述的数据组织关系和编排方式的具体实现。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 1, '在地理信息系统中，最常用的两类空间数据结构是什么？', '矢量数据结构和栅格数据结构。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 2, '矢量数据结构通过记录_____及其关系来表示地理实体。', '实体坐标', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 3, '矢量数据结构按是否明确表示空间关系，可分为实体数据结构和_____。', '拓扑数据结构', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 4, '实体数据结构（spaghetti）的主要单位是什么？', '多边形单元。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 5, '实体数据结构的主要缺点之一是相邻多边形的公共边界需要_____，导致数据冗余。', '数字化两遍', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 6, '实体数据结构是否包含多边形的邻域信息和拓扑关系？', '不包含。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 7, '拓扑关系是一种对空间结构关系进行明确定义的_____方法。', '数学', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 8, '拓扑数据结构的共同特点是：点相互独立，点连成线，线构成_____。', '面', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 9, '拓扑数据结构中最重要的特征是什么？', '具有拓扑编辑功能。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 10, '索引式矢量数据结构如何消除相邻多边形边界的数据冗余？', '通过建立多边形与边界线、边界线与点之间的树状索引。 ', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 11, '在 DIME 编码中，任何一条线段是由_____和相邻多边形来定义的。', '顺序的两点', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 12, '链状双重独立编码结构相对于 DIME 的改进是什么？', '将若干直线段合为一个具有多个中间点的弧段（链段）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 13, '网络数据结构由边、交汇点以及_____组成。', '连通性规则', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 14, '网络建模中，强调边与边之间拓扑关系的是哪种网络？', '逻辑网络。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 15, '栅格数据结构中，位置是通过什么来确定的？', '行列号。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 16, '栅格数据结构的显著特点是：属性明显，_____。', '定位隐含', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 17, '完全栅格数据组织的三个基本方式是：基于像元、基于层和_____。', '基于面域', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 18, '游程长度编码（Run-length encoding）压缩数据的原理是什么？', '记录相同属性值及其重复的个数（行程）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 19, '游程长度编码压缩效率最高的情况是_____。', '原始栅格类型越简单（类型面积较大）', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 20, '四叉树数据结构的基本思想是将图像等分为哪四个子象限？', '左上 (NW)、右上 (NE)、左下 (SW)、右下 (SE)。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 21, '为了保证四叉树能不断分解，要求栅格单元数必须满足什么条件？', '$2^n \times 2^n$ ($n$ 为分割次数)。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 22, '线性四叉树叶结点的十进制地址码通常称为什么？', 'Morton 码（简称 MD 码）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 23, 'MD 码是通过对栅格单元的_____进行二进制“位”交叉运算得到的。', '行列号', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 24, '链码（Freeman 码）通常用于对什么进行编码？', '栅格中的线或多边形边界。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 25, '在链码结构中，每个后续点可能位于前继点的几个基本方向之一？', '8 个。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 26, '影像金字塔结构中，哪一层存储分辨率最高的数据？', '金字塔的底层。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 27, '在电子地图服务中，金字塔结构主要用于组织什么数据？', '地图切片（Tile）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 28, '矢量数据结构的缺点之一是空间分析技术（如叠置分析）比较_____。', '复杂', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 29, '为什么栅格数据结构比较容易和遥感相结合？', '因为遥感影像本身就是以像元为单位的栅格结构。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 30, '矢量数据结构具有“位置明显、_____”的特点。', '属性隐含', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 31, '栅格数据若要提高一倍表达精度，数据量会增加几倍？', '3 倍。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 32, '矢栅一体化数据结构的设计基础是什么？', '多级格网方法、三个基本约定和线性四叉树编码。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 33, '矢栅一体化结构中的三级格网分别是粗格网、基本格网和_____。', '细分格网', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 34, '在矢量转栅格时，_____决定了数据的输出精度。', '栅格像元的大小', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 35, '多边形面域向栅格转换的过程又称为什么？', '多边形填充。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 36, '列举两种常用的多边形填充算法。', '扫描线法、射线法（或内部点扩散法）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 37, '栅格向矢量转换前，若线画宽度占据多个栅格，需要进行什么处理？', '细化处理。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 38, 'Voronoi 单元（泰森多边形）是通过样点之间的什么线生成的？', '垂直平分线。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 39, 'TIN（不规则三角网）数据结构通常有以三角形为对象和_____为对象两种组织方式。', '以特征点', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 40, '以三角形为基本对象的 TIN 数据结构中，每个三角形记录通常包含哪些拓扑信息？', '三角形顶点 ID 和邻接三角形 ID。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 41, '为什么以特征点为对象的 TIN 结构适合线性内插分析？', '因为它记录了点与点之间的相连关系（三角形边）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 42, '拓扑数据结构中，线段的左右多边形信息用于确定实体的_____关系。', '邻接', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 43, '在栅格游程长度编码中，数据对 $(s_i, l_i)$ 的 $s_i$ 代表什么？', '属性值。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 44, '四叉树自上而下分割法的主要缺点是什么？', '运算量大，因为需要重复检查格网属性值。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 45, '网络数据结构中，用于存储节点空间位置的文件称为什么？', '节点文件。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 46, '在 GIS 应用中，污染扩散模拟通常采用哪种数据结构？', '栅格数据结构。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 47, '在 GIS 应用中，规划选址和路径分析通常采用哪种数据结构？', '矢量数据结构。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 48, '拓扑数据结构中的“弧段”是指始于起始结点、止于终止结点的_____。', '有向曲线', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 49, '栅格数据结构中，线状地物在每个栅格单元中最多有多少个相邻同类单元？', '2 个。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 50, '二维行程编码是在生成线性四叉树后，通过合并什么来进一步压缩数据的？', '前后属性值相同的叶结点。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 51, '在矢量转栅格的点要素转换中，“众数原则”指的是什么？', '取落入像元中出现频率最高的属性值作为像元值。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 52, '矢栅一体化结构中，表示基本栅格内局部编码的 Morton 码符号是什么？', '$M_2$。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 53, 'Freeman 链码起始点的寻找通常遵循什么原则？', '从上到下、从左到右。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 54, '如果多边形中含有“洞”，在链状双重独立编码的多边形文件中如何记录？', '该“洞”的面积为负，且组成的弧段号前冠以负号。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 55, '哪种矢量结构特别适用于城市地籍宗地的管理？', 'DIME（双重独立编码结构）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 56, '栅格数据结构数学模拟方便的优点对应的代价是什么？', '数据量大、难以建立拓扑关系。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 57, '影像金字塔中，层数增加对应数据分辨率如何变化？', '分辨率依次降低（或变粗）。', datetime('now'));
insert into cards (chapter_id, card_index, front, back, updated_at) values ('chapter-4', 58, '在建立拓扑结构时，若数字化弧段在同一结点坐标偏差过大，应如何处理？', '需要重新数字化该弧段。', datetime('now'));
